# Generated by Django 6.1.1 on 2026-09-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='admin_password',
            field=models.CharField(default='admin123', max_length=128),
            preserve_default=False,
        ),
    ]
