# Generated by Django 6.1.1 on 2026-09-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_id', '0002_department_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='submission_year',
            field=models.PositiveIntegerField(default=2026),
        ),
    ]
